export const ELEMENT_DEFINITIONS: Record<string, string> = {
  // ── World 1 base elements ─────────────────────────────────────────────────
  Wind:          'Moving air created by differences in atmospheric pressure.',
  Earth:         'Solid ground and mineral matter that forms the planet\'s crust.',
  Fire:          'Rapid combustion that releases heat, light, and energy.',
  Water:         'A transparent liquid compound essential to all known life.',

  // ── World 2 base elements ─────────────────────────────────────────────────
  Wood:          'A hard, fibrous material harvested from tree trunks and branches.',
  Metal:         'A solid, conductive material valued for strength and malleability.',
  Glass:         'A hard, transparent material produced by melting silica sand.',
  Rubber:        'A flexible, elastic material from tree sap or synthetic polymers.',
  Plastic:       'A lightweight, moldable synthetic material made from polymers.',

  // ── World 3 base elements ─────────────────────────────────────────────────
  Electricity:   'Energy from the flow of electric charge through a conductor.',
  Fuel:          'A substance burned to release stored chemical energy as heat.',

  // ── World 4 base elements ─────────────────────────────────────────────────
  Heat:          'Thermal energy transferred from a hotter object to a cooler one.',
  Gas:           'Matter with no fixed shape or volume that fills its container.',
  Carbon:        'A nonmetal element forming the backbone of all organic molecules.',
  Acid:          'A corrosive substance with pH below 7 that donates protons.',
  Base:          'A substance with pH above 7 that neutralizes acids.',

  // ── World 5 base elements ─────────────────────────────────────────────────
  Particle:      'The smallest discrete unit of matter, such as an electron or quark.',
  Wave:          'A periodic disturbance that propagates energy through a medium.',
  Energy:        'The capacity to do work, existing as heat, light, motion, or mass.',
  Void:          'A region of empty space containing no matter or radiation.',
  Spin:          'The intrinsic angular momentum property of a subatomic particle.',
  Field:         'A region of space where a force acts on any particle within it.',
  Observer:      'An entity whose measurement collapses quantum probability into an outcome.',
  Charge:        'A fundamental property of matter that drives electromagnetic forces.',

  // ── World 6 base elements ─────────────────────────────────────────────────
  Cell:          'The basic structural and functional unit of all living organisms.',
  Light:         'Electromagnetic radiation visible to the human eye.',
  Oxygen:        'A reactive gas essential for cellular respiration and combustion.',
  Nitrogen:      'An inert gas making up 78% of Earth\'s atmosphere.',
  Enzyme:        'A protein that speeds up chemical reactions in living cells.',

  // ── World 7 base elements ─────────────────────────────────────────────────
  Stone:         'A solid, dense aggregate of minerals found in the Earth\'s crust.',
  Knowledge:     'Organized information and understanding gained through experience.',
  Labor:         'Physical or mental effort applied to produce goods or outcomes.',
  Time:          'The continuous progression of events from past through present to future.',
  Soil:          'The top layer of Earth, rich in organic matter and minerals.',
  Spirit:        'The non-physical essence believed to animate and guide living beings.',

  // ── World 8 base elements ─────────────────────────────────────────────────
  Gravity:       'The force that attracts mass toward other mass across space.',
  Plasma:        'The fourth state of matter — a superheated ionized gas.',
  Dust:          'Fine particles of rock, mineral, or cosmic material.',
  Ice:           'Water in its solid crystalline state below 0°C.',
  Magnetism:     'A force produced by moving electric charges that attracts or repels.',
  Radiation:     'Energy emitted as electromagnetic waves or high-energy particles.',
  'Dark Matter': 'Invisible matter that exerts gravity but does not emit light.',

  // ── World 1 combos ────────────────────────────────────────────────────────
  Mud:           'A wet mixture of earth and water, found near rivers and wetlands.',
  Lightning:     'A rapid, massive electrical discharge between clouds and the ground.',
  Steam:         'Water converted to invisible vapor by boiling — drives turbines and engines.',
  Lava:          'Molten rock expelled from a volcano onto Earth\'s surface.',
  Storm:         'A violent weather event combining strong winds, rain, and atmospheric turbulence.',
  Sand:          'Fine granular rock fragments worn down by wind, water, and time.',
  Clay:          'A fine-grained earth that becomes hard and rigid when heated.',
  Life:          'The biological condition of growth, metabolism, and self-replication.',

  // ── World 2 combos ────────────────────────────────────────────────────────
  Plywood:       'Engineered wood made from thin sheets bonded under pressure and heat.',
  Mirror:        'A glass surface coated to reflect images with high clarity.',
  Goggle:        'Protective eyewear that shields the eyes from debris or chemicals.',
  Seal:          'A gasket material used to close gaps and prevent fluid leaks.',
  Crate:         'A sturdy wooden or plastic box used for shipping and storage.',
  Window:        'A framed pane of glass that admits light while blocking wind.',
  Tire:          'A rubber ring mounted on a wheel for traction and shock absorption.',
  Case:          'A protective enclosure designed to house and shield components.',
  Slingshot:     'A Y-shaped tool that launches projectiles using elastic tension.',
  Laminate:      'Layers of material bonded together for added strength and durability.',
  Frame:         'A rigid structure that supports or surrounds another component.',
  Gear:          'A toothed wheel that meshes with others to transfer motion and torque.',
  Greenhouse:    'A glass structure that traps solar heat to cultivate plants year-round.',
  Spring:        'A coiled metal element that stores and releases mechanical energy.',
  Bumper:        'A protective barrier designed to absorb and distribute impact force.',
  Machine:       'A device with moving parts that performs specific mechanical tasks.',
  Device:        'A purpose-built tool or instrument designed for a specific function.',
  Core:          'The central, essential component of any structure or system.',
  Clamp:         'A fastening tool that grips and holds objects firmly in place.',
  Fixture:       'A permanent component fixed securely to a structure or surface.',
  Grip:          'A surface or handle designed for secure, reliable holding.',
  Cabinet:       'An enclosed storage unit with compartments and doors.',
  Console:       'A control panel or housing for electronic or mechanical systems.',
  Toolkit:       'A curated set of tools organized for a specific trade or task.',

  // ── World 3 combos ────────────────────────────────────────────────────────
  Wire:          'A thin, flexible metal conductor for carrying electrical current.',
  Gasket:        'A sealing ring that prevents leaks between two mating surfaces.',
  Pipe:          'A cylindrical conduit for transporting fluids or gases under pressure.',
  Switch:        'A device that opens or closes an electrical circuit on command.',
  Coil:          'A wound spiral of wire used in motors, transformers, and inductors.',
  Tank:          'A sealed container for storing liquids or gases under pressure.',
  Valve:         'A mechanical device that controls or regulates fluid and gas flow.',
  Flare:         'A burst of bright, intense light used as a signal or warning.',
  Cable:         'A thick bundle of insulated wires for power or data transmission.',
  Motor:         'A device that converts electrical energy into mechanical rotation.',
  Sensor:        'An instrument that detects and measures physical or chemical conditions.',
  Pump:          'A machine that moves fluids or gases by applying mechanical pressure.',
  Filter:        'A device that removes impurities from a fluid, gas, or signal.',
  Generator:     'A machine that converts mechanical motion into electrical energy.',
  Reactor:       'A vessel where nuclear or chemical reactions are controlled and sustained.',
  Engine:        'A machine that converts fuel into mechanical force and motion.',
  Chip:          'A tiny integrated circuit etched onto a semiconductor wafer.',
  Screen:        'A flat surface that displays images or data electronically.',
  Burner:        'A component that produces a controlled, steady flame from fuel.',
  Welder:        'A tool that joins metal pieces using intense heat from electricity.',
  Solenoid:      'A coil of wire that acts as a linear electromagnet when energized.',
  Lantern:       'A portable light source enclosed in a transparent protective case.',
  'Vacuum Tube': 'An electron valve that amplifies or switches electrical signals.',
  Canister:      'A sealed cylindrical container for pressurized or hazardous substances.',
  Gauge:         'An instrument for measuring and displaying a physical quantity.',
  Lighthouse:    'A tall coastal tower with a powerful light beam to guide ships.',
  Visor:         'A transparent protective screen shielding the face or eyes.',
  Dynamo:        'A generator that converts mechanical rotation into direct electrical current.',
  Battery:       'A device that stores chemical energy and releases it as electricity.',
  Relay:         'An electrically operated switch controlled by a separate circuit.',
  Circuit:       'A closed loop path through which electric current flows continuously.',
  Hose:          'A flexible tube used to direct the flow of liquids or gases.',
  Piston:        'A sliding component inside a cylinder that transfers mechanical force.',
  Cartridge:     'A sealed container holding a ready-to-use chemical or electronic component.',
  Nozzle:        'A spout that shapes and directs the flow of a fluid or gas.',
  Turbine:       'A rotary machine driven by fluid flow to generate mechanical power.',
  Amplifier:     'A device that increases the power or strength of an electrical signal.',
  Transformer:   'A device that changes the voltage of an alternating electrical current.',
  Compressor:    'A machine that increases the pressure of a gas by reducing its volume.',
  Furnace:       'A high-temperature chamber for heating, melting, or smelting materials.',
  Regulator:     'A device that maintains a constant level of pressure or voltage.',
  'Pressure Vessel': 'A reinforced container designed to hold substances at high pressure.',
  Terminal:      'An endpoint connector in an electrical circuit or power system.',
  Exhaust:       'Waste gases expelled from an engine after combustion is complete.',
  Floodlight:    'A powerful wide-angled lamp for illuminating large outdoor areas.',
  Cockpit:       'The control compartment of an aircraft, ship, or vehicle.',
  Processor:     'A chip that executes computational instructions and processes data.',
  Powercore:     'The central energy unit that powers a large or complex system.',
  Rig:           'A large, complex assembly of machinery for drilling or power generation.',
  Capsule:       'A sealed, self-contained module for housing systems or people.',
  Network:       'An interconnected system of nodes that exchanges data or electricity.',
  System:        'A complete, integrated assembly performing a unified purpose.',

  // ── World 4 combos ────────────────────────────────────────────────────────
  Brine:         'Highly concentrated salt water, found in oceans and salt flats.',
  Vapor:         'Water in gaseous form, created by evaporation or boiling.',
  Oxide:         'A compound formed when an element chemically bonds with oxygen.',
  Limestone:     'A sedimentary rock composed mainly of calcium carbonate.',
  Salt:          'An ionic compound produced when an acid reacts with a base.',
  Ink:           'A pigmented liquid used for writing, printing, or drawing.',
  Alloy:         'A metal made by fusing two or more metallic elements together.',
  Foam:          'A light, airy mass of gas bubbles trapped in liquid or solid.',
  Resin:         'A sticky polymer solid used in adhesives, coatings, and plastics.',
  Etch:          'The process of cutting or patterning a surface using acid or chemicals.',
  Alkali:        'A soluble base that produces hydroxide ions when dissolved in water.',
  Coal:          'A combustible black rock formed from compressed ancient organic matter.',
  'Arc Plasma':  'An ionized gas generated by an intense electrical arc discharge.',
  Slurry:        'A thick fluid suspension of fine solid particles in a liquid.',
  Potion:        'A liquid mixture of reactive chemicals prepared for a specific effect.',
  Compound:      'A substance of two or more elements chemically bonded together.',
  Solvent:       'A liquid that dissolves other substances to form a solution.',
  Converter:     'A device that transforms one substance or energy form into another.',
  Formula:       'A precise expression defining the composition of a chemical substance.',
  Mixture:       'Two or more substances combined without a chemical reaction.',
  Solution:      'A homogeneous mixture with a solute fully dissolved in a solvent.',
  Rust:          'Iron oxide formed when iron reacts with water and atmospheric oxygen.',
  Blight:        'A rapid, destructive disease or corrosion affecting materials or organisms.',
  Smog:          'Dense air pollution from industrial emissions that reduces visibility.',
  Ingot:         'A block of purified metal cast for storage or further processing.',
  'Acid Cloud':  'A toxic atmospheric mass formed by corrosive gaseous emissions.',
  Cinder:        'Partially burned material or ash remaining after combustion.',
  Tonic:         'A stimulating liquid solution with therapeutic or restorative properties.',
  Calcium:       'An essential mineral element vital for bones, teeth, and cellular function.',
  Deposit:       'A layer of mineral or sedimentary material accumulated over time.',
  Cement:        'A fine gray powder that hardens into stone when mixed with water.',
  Haze:          'A light atmospheric cloudiness from suspended particles or humidity.',
  Dross:         'Waste slag or impurities skimmed off the surface of molten metal.',
  Spray:         'A fine mist of liquid particles dispersed by pressure.',
  Pigment:       'A colored substance that absorbs specific light wavelengths to produce color.',
  Reagent:       'A substance used in chemical reactions to detect or measure another.',
  Lotion:        'A thin liquid applied to skin for cleansing or therapeutic treatment.',
  Rinse:         'A wash of water or liquid used to remove chemical residue.',
  Antidote:      'A substance that counteracts the toxic effect of a poison or acid.',
  Patina:        'A green or blue-gray coating that forms on copper and brass through prolonged chemical oxidation.',
  Tarnish:       'A thin layer of corrosion dulling a metal\'s surface over time.',
  Calciner:      'An industrial furnace for chemically decomposing materials using intense heat.',
  Vinegar:       'A dilute acetic acid solution produced by fermentation.',
  Corrode:       'The process of metal being chemically worn away by oxidation or acids.',
  Corrosion:     'The gradual chemical deterioration of metal from environmental reactions.',
  Char:          'Partially combusted organic material reduced to black carbon.',
  Charcoal:      'A porous black carbon material made by burning wood without oxygen.',

  // ── World 5 combos ────────────────────────────────────────────────────────
  Atom:          'The smallest unit of an element retaining its chemical properties.',
  Electron:      'A negatively charged subatomic particle orbiting an atomic nucleus.',
  Photon:        'A massless particle of light that carries electromagnetic energy.',
  Quantum:       'The smallest discrete unit of a physical quantity in quantum theory.',
  Qubit:         'The basic unit of quantum information, existing in superposition.',
  Ion:           'An atom or molecule with a net positive or negative electric charge.',
  Aura:          'A distinctive field or energy emanation surrounding a particle or body.',
  Anomaly:       'A measurable deviation from what is expected in a physical system.',
  Arc:           'A curved path traced by a charged particle through a field.',
  Collider:      'A particle accelerator that smashes beams of particles together.',
  'Dark Energy': 'A mysterious force causing the accelerating expansion of the universe.',
  'Dark Field':  'A region where dark matter\'s gravitational influence dominates.',
  Echo:          'A repeating signal pattern caused by wave reflection.',
  Entanglement:  'A quantum link where two particles share correlated states instantly.',
  Event:         'A specific point in spacetime defined by its position and time.',
  Fold:          'A bending in spacetime geometry caused by massive objects.',
  Hadron:        'A composite particle made of quarks bound by the strong force.',
  Momentum:      'The product of an object\'s mass and velocity.',
  Pulse:         'A brief burst of energy, radiation, or wave activity.',
  Resonance:     'A phenomenon where a system absorbs energy at its natural frequency.',
  Singularity:   'A point of infinite density where normal physics breaks down.',
  Spectrum:      'The full range of electromagnetic radiation ordered by wavelength.',
  String:        'A theoretical one-dimensional vibrating filament of energy in string theory.',
  Superposition: 'The quantum state where a particle exists in multiple states simultaneously.',
  'Unified Field':'A hypothetical framework linking all fundamental forces of nature.',
  Vacuum:        'A region of space with the lowest possible energy, nearly empty.',
  Vortex:        'A spiraling flow of energy or matter around an axis.',
  'Wave Function':'A mathematical description of a quantum particle\'s possible states.',
  Wavicle:       'A particle that exhibits both wave and particle behavior.',
  Gyroscope:     'A device using rotational spin to maintain orientation in space.',
  'Solenoid Field':'The directed magnetic field produced by a current-carrying solenoid coil.',
  Torque:        'A rotational force that causes an object to spin around an axis.',
  Spacetime:     'The four-dimensional framework combining three spatial dimensions with time.',
  'Many Worlds': 'The quantum interpretation where every measurement creates a branching universe.',
  Schrodinger:   'A thought experiment illustrating quantum superposition using a cat in a box.',
  'God Particle': 'A nickname for the Higgs boson, the particle that gives others mass.',
  'Quantum Leap': 'An abrupt, discontinuous transition between quantum energy states.',
  Signal:        'Information transmitted as a wave or pulse through a medium.',
  Flash:         'A brief, intense burst of electromagnetic energy or light.',
  Beacon:        'A directed signal used for navigation or communication.',

  // ── World 6 combos ────────────────────────────────────────────────────────
  Bacteria:      'Single-celled microorganisms found in nearly every environment on Earth.',
  Algae:         'Photosynthetic organisms ranging from single-celled to large seaweed.',
  Seed:          'A plant embryo enclosed in a protective coat, ready to germinate.',
  Leaf:          'A flat, thin plant organ that captures sunlight for photosynthesis.',
  DNA:           'The double-helix molecule that encodes genetic information for all life.',
  Genome:        'The complete set of DNA instructions in a living organism.',
  Chlorophyll:   'The green pigment in plants that captures sunlight for photosynthesis.',
  Glucose:       'A simple sugar that serves as the primary energy source for cells.',
  Blood:         'The fluid that circulates oxygen, nutrients, and hormones through the body.',
  Brain:         'The central nervous organ that processes thought, sensation, and control.',
  Cortex:        'The outer layer of the brain responsible for higher cognition.',
  Consciousness: 'The state of being aware and experiencing subjective sensation.',
  Membrane:      'A thin, flexible layer that controls what enters or exits a cell.',
  Egg:           'A reproductive cell or structure containing an embryo and nutrients.',
  Embryo:        'An organism in its earliest stage of development after fertilization.',
  Antibody:      'A protein the immune system produces to neutralize specific pathogens.',
  'Immune Cell': 'A white blood cell that detects and destroys infections or tumors.',
  Hormone:       'A chemical messenger released into the bloodstream to regulate body functions.',
  Bile:          'A digestive fluid produced by the liver to break down fats.',
  Sweat:         'A salt-water fluid secreted by skin glands to regulate body temperature.',
  Fever:         'An elevated body temperature triggered by the immune system fighting infection.',
  Breath:        'The rhythmic exchange of oxygen and carbon dioxide in the lungs.',
  Ecosystem:     'A community of living organisms interacting with their environment.',
  Evolution:     'The gradual change of populations over generations through natural selection.',
  Symbiosis:     'A close, long-term interaction between two species for mutual benefit.',
  Fungi:         'Organisms like mushrooms and mold that break down organic matter.',
  Toxin:         'A poisonous substance produced by living cells or microorganisms.',
  Aerosol:       'Fine liquid or solid particles suspended in a gaseous medium.',
  Bubble:        'A thin sphere of liquid enclosing a pocket of gas.',
  Fossil:        'The preserved remains of ancient organisms embedded in rock.',
  Amber:         'Ancient tree resin fossilized over millions of years, preserving organisms.',
  Crop:          'A plant cultivated at large scale as food or raw material.',
  Activator:     'A molecule that binds to a protein to increase its biological activity.',
  Digest:        'The process of breaking down food into absorbable nutrients.',
  Sting:         'A sharp pain or defensive chemical weapon delivered by an organism.',
  Blister:       'A fluid-filled pocket of skin formed by friction, heat, or chemical damage.',
  Warmth:        'A gentle, moderate level of heat that promotes comfort or growth.',
  Sunburn:       'Skin damage caused by overexposure to ultraviolet radiation.',
  'Life Force':  'The vital energy believed to animate and sustain living organisms.',
  Vision:        'The ability to perceive light and form images in the mind.',
  Sight:         'The sense of perceiving light, color, and shape through the eyes.',
  Geyser:        'A hot spring that periodically erupts boiling water and steam.',
  Cloud:         'A visible mass of water droplets or ice crystals suspended in the atmosphere.',
  Flood:         'An overflow of water onto land that is normally dry.',
  Vent:          'An opening that allows the release of pressure, gas, or fluid.',

  // ── World 7 combos ────────────────────────────────────────────────────────
  Blade:         'A sharp-edged tool or weapon for cutting, crafted from hard materials.',
  Axe:           'A chopping tool with a heavy metal head fixed to a wooden handle.',
  Hammer:        'A weighted tool used to drive nails, shape metal, or break stone.',
  Wheel:         'A circular object that rotates on an axle, enabling movement.',
  Boat:          'A small watercraft used for transport across rivers or coastal waters.',
  Canoe:         'A lightweight narrow boat propelled by paddles.',
  Bridge:        'A structure spanning an obstacle like water or a gap to allow crossing.',
  Well:          'A shaft sunk into the ground to access underground water.',
  Arch:          'A curved structural element that distributes weight to its supports.',
  Tower:         'A tall, narrow structure built from stone or wood for defense or observation.',
  Farm:          'Land cultivated to grow food crops or raise livestock.',
  Harvest:       'The gathering of mature crops from agricultural land.',
  Irrigation:    'The controlled supply of water to agricultural land for growing crops.',
  Aqueduct:      'An ancient engineered channel for carrying water over long distances.',
  Dam:           'A barrier built across a river to control water flow and generate power.',
  Mine:          'An excavation into the earth to extract minerals and ores.',
  Forge:         'A furnace or workshop for heating and shaping metal.',
  Sword:         'A long bladed weapon with a handle, used for combat.',
  Armor:         'Protective covering worn in battle to deflect or absorb blows.',
  Coin:          'A standardized metal disc used as a medium of exchange.',
  Market:        'A place where goods and services are bought and sold.',
  Map:           'A visual representation of an area used for navigation and planning.',
  Calendar:      'A system for organizing time into days, months, and years.',
  Scroll:        'A roll of parchment or papyrus used for writing and record-keeping.',
  Tablet:        'A flat slab of stone or clay used for writing in ancient times.',
  Manuscript:    'A handwritten document or book, often ancient and rare.',
  Library:       'A curated collection of written works for study and reference.',
  Lumber:        'Processed timber cut into planks for construction.',
  Stump:         'The remaining base of a tree after it has been cut down.',
  Gravel:        'Small loose stones used in construction and surfacing.',
  Craft:         'A skilled trade or art requiring dexterity and practiced knowledge.',
  Totem:         'A sacred object or symbol representing a clan\'s spirit or ancestor.',
  Shrine:        'A sacred site or structure dedicated to a deity or honored ancestor.',
  Temple:        'A building dedicated to religious worship and sacred ceremonies.',
  Cathedral:     'A large, grand church that is the seat of a bishop.',
  Idol:          'A physical image or object worshipped as a representation of a deity.',
  Ancestor:      'A person from whom one is descended, honored in many cultures.',
  Legend:        'A traditional story passed down generations, often of heroic deeds.',
  Wisdom:        'Deep understanding and good judgment gained through experience.',
  Army:          'An organized military force trained and equipped for warfare.',
  Empire:        'A large political entity ruling many territories under one authority.',
  Fleet:         'A group of ships or vehicles operating under unified command.',
  Colosseum:     'A large ancient amphitheater used for public spectacles and gladiator combat.',
  Dynasty:       'A succession of rulers from the same family line over generations.',
  'Golden Age':  'A period of great prosperity, creativity, and cultural flourishing.',
  Civilization:  'A complex society with cities, writing, law, and organized governance.',
  Crown:         'A ceremonial headpiece symbolizing royal authority and power.',
  Longbow:       'A tall wooden bow capable of shooting arrows with great range.',
  Horizon:       'The line where Earth\'s surface and sky appear to meet.',
  Torch:         'A portable light source made with a burning fuel-soaked material.',
  'Spirit Well': 'A sacred site believed to channel spiritual energy or ancestral power.',
  Magnet:        'An object that produces a magnetic field attracting ferromagnetic materials.',
  Tunnel:        'An underground passage cut through earth or rock.',
  Harbor:        'A sheltered coastal area where ships dock for loading and protection.',
  Sextant:       'A navigational instrument for measuring the angle of celestial objects.',

  // ── World 8 combos ────────────────────────────────────────────────────────
  'Dark Halo':   'A ring of dark matter surrounding a galaxy, detectable only by gravity.',
  'Dark Mass':   'A concentration of invisible dark matter inferred from gravitational lensing.',
  'Shadow Flare':'An energetic burst absorbed or scattered by dark matter clouds.',
  Abyss:         'An unfathomably deep region of space devoid of matter or light.',
  'Dead Zone':   'A region in space where magnetic fields cancel and particles cease to flow.',
  Debris:        'Scattered fragments of rock, ice, and dust from shattered cosmic bodies.',
  Decay:         'The radioactive breakdown of unstable atomic nuclei over time.',
  'Deep Space':  'Regions of space far from any star, galaxy, or known matter.',
  'Dust Age':    'A cosmic era dominated by the accumulation of interstellar dust clouds.',
  'Dust Storm':  'A cloud of accelerated dust particles swept by magnetic or plasma winds.',
  'Dust Web':    'A filamentary structure of cosmic dust tracing dark matter scaffolding.',
  Epoch:         'A distinct, defined period in cosmic or geological history.',
  Eruption:      'A violent ejection of plasma, gas, or material from a stellar body.',
  'Event Horizon':'The boundary around a black hole beyond which nothing can escape.',
  'Ancient Light':'Photons that have traveled billions of years to reach us from the early universe.',
  Frost:         'Ice crystals deposited on a surface when temperature drops below freezing.',
  'Gas Cloud':   'A vast, diffuse cloud of hydrogen and helium in interstellar space.',
  'Ghost Star':  'A dim stellar remnant or phantom image left by a former star.',
  Glacier:       'A large, slow-moving mass of ice formed from compressed snowfall.',
  'Half-Life':   'The time required for half of a radioactive element\'s atoms to decay.',
  'Ice Radiation':'Radiation that freezes or alters the structure of ice in space.',
  Laser:         'Amplified, coherent light of a single wavelength focused into a beam.',
  Lensing:       'The bending of light around a massive object due to gravity.',
  Magnetar:      'An extremely dense neutron star with a powerful magnetic field.',
  'Magnetic Storm':'A disturbance in a planet\'s magnetosphere caused by solar wind.',
  Moon:          'A natural satellite orbiting a planet, held in place by gravity.',
  Nebula:        'A cloud of gas and dust in space, often the birthplace of new stars.',
  'Neutron Star': 'A collapsed stellar core composed almost entirely of tightly packed neutrons.',
  Orbit:         'The curved path of an object moving around a larger body in space.',
  Permafrost:    'Permanently frozen ground found beneath the surface in polar regions.',
  Planet:        'A large spherical body orbiting a star, shaped by its own gravity.',
  'Plasma Age':  'An early cosmic era when the universe consisted entirely of hot plasma.',
  'Polar Cap':   'A region of ice at the magnetic pole of a planet or moon.',
  Pulsar:        'A rapidly rotating neutron star that emits regular pulses of radiation.',
  Asteroid:      'A small rocky body orbiting the Sun, leftover from the solar system\'s formation.',
  Shadow:        'A dark region caused when an object blocks a light source.',
  Shockwave:     'A supersonic pressure wave moving through space from an explosion.',
  'Solar Wind':  'A stream of charged particles continuously emitted by the Sun.',
  'Emission Line':'A bright line in a spectrum produced by excited atoms releasing photons.',
  Star:          'A massive ball of plasma sustained by nuclear fusion in its core.',
  Tail:          'The luminous stream of gas and dust trailing a comet.',
  'Time Dilation':'The slowing of time for an object moving fast or in strong gravity.',
  Blazar:        'A highly energetic jet of plasma aimed directly toward Earth from a galaxy.',
  'Comet Storm': 'A barrage of icy comets sent inward by gravitational disturbance.',
  'Dark Web':    'The vast invisible cosmic web of dark matter linking galaxy clusters.',
  'Gamma Burst': 'The most powerful electromagnetic explosion in the observable universe.',
  'Ice Planet':  'A planetary body dominated by thick layers of frozen water or gases.',
  Magnetosphere: 'The region of space around a body dominated by its magnetic field.',
  'Nebula Core': 'The dense, hot center of a nebula, often collapsing to form a star.',
  Protostar:     'A collapsing cloud of gas and dust in the early stage of stellar formation.',
  Quasar:        'An extremely luminous galactic nucleus powered by a supermassive black hole.',
  'Solar System':'A star and all the bodies bound to it by gravity.',
  Supernova:     'A cataclysmic explosion that destroys a massive star at the end of its life.',
  'Time Rift':   'A hypothetical tear in spacetime caused by extreme gravitational or energy events.',
  'Dark Galaxy': 'A galaxy composed mostly of dark matter with few visible stars.',
  Galaxy:        'A gravitationally bound system of billions of stars, gas, and dust.',
  'Ice Comet':   'A small, icy body that develops a bright tail as it nears the Sun.',
  'Magnetar Storm':'An intense burst of radiation caused by a magnetar\'s magnetic field fracturing.',
  'Stellar Nursery':'A dense region of gas and dust where new stars are actively forming.',
  'White Dwarf': 'The dense, cooling core left behind after a medium-sized star dies.',
  'Cosmic Web':  'The large-scale structure of the universe, consisting of filaments and voids.',
  'Dark Collapse':'A hypothetical catastrophic event where dark matter destabilizes spacetime.',
  'Red Giant':   'A large, cool star in the late stage of its life, expanded to enormous size.',
  'Cosmic Dawn': 'The era when the first stars and galaxies illuminated the early universe.',
  Entropy:       'The measure of disorder in a system, which always increases over time.',
  Multiverse:    'The theoretical collection of all possible universes beyond our own.',
  'Dark Universe':'A hypothetical cosmos dominated entirely by dark matter and dark energy.',
  'Observable Universe':'The region of the universe from which light has had time to reach us.',
  Inflation:     'The rapid exponential expansion of the universe in its very first moments.',
  'Heat Death':  'The theoretical final state of the universe when all energy reaches equilibrium.',
  'Big Bang':    'The singular event approximately 13.8 billion years ago that began the universe.',
  'Cryo Shadow': 'A dark, frozen region in space shielded from all stellar radiation.',
  'Void Era':    'A theoretical future age when the universe consists only of empty void.',
};
