export interface CatalogRecipe {
  name: string;
  ingredients: string[];
  world: number;
}

export const RECIPE_CATALOG: CatalogRecipe[] = [
  // ── World 1 — Nature Lab ───────────────────────────────────────────────────
  { world: 1, name: 'Mud',       ingredients: ['Earth', 'Water'] },
  { world: 1, name: 'Lightning', ingredients: ['Wind', 'Fire'] },
  { world: 1, name: 'Dust',      ingredients: ['Wind', 'Earth'] },
  { world: 1, name: 'Steam',     ingredients: ['Fire', 'Water'] },
  { world: 1, name: 'Ice',       ingredients: ['Wind', 'Water'] },
  { world: 1, name: 'Lava',      ingredients: ['Earth', 'Fire'] },
  { world: 1, name: 'Storm',     ingredients: ['Wind', 'Fire', 'Water'] },
  { world: 1, name: 'Sand',      ingredients: ['Wind', 'Earth', 'Fire'] },
  { world: 1, name: 'Clay',      ingredients: ['Earth', 'Fire', 'Water'] },
  { world: 1, name: 'Life',      ingredients: ['Wind', 'Earth', 'Water'] },
  { world: 1, name: 'Energy',    ingredients: ['Wind', 'Earth', 'Fire', 'Water'] },

  // ── World 2 — Materials Workshop ──────────────────────────────────────────
  { world: 2, name: 'Plywood',    ingredients: ['Wood', 'Metal'] },
  { world: 2, name: 'Mirror',     ingredients: ['Metal', 'Glass'] },
  { world: 2, name: 'Goggle',     ingredients: ['Glass', 'Rubber'] },
  { world: 2, name: 'Seal',       ingredients: ['Rubber', 'Plastic'] },
  { world: 2, name: 'Crate',      ingredients: ['Wood', 'Plastic'] },
  { world: 2, name: 'Window',     ingredients: ['Wood', 'Glass'] },
  { world: 2, name: 'Tire',       ingredients: ['Metal', 'Rubber'] },
  { world: 2, name: 'Case',       ingredients: ['Metal', 'Plastic'] },
  { world: 2, name: 'Slingshot',  ingredients: ['Wood', 'Rubber'] },
  { world: 2, name: 'Laminate',   ingredients: ['Glass', 'Plastic'] },
  { world: 2, name: 'Frame',      ingredients: ['Wood', 'Metal', 'Glass'] },
  { world: 2, name: 'Gear',       ingredients: ['Metal', 'Rubber', 'Plastic'] },
  { world: 2, name: 'Greenhouse', ingredients: ['Wood', 'Glass', 'Plastic'] },
  { world: 2, name: 'Spring',     ingredients: ['Metal', 'Glass', 'Rubber'] },
  { world: 2, name: 'Bumper',     ingredients: ['Wood', 'Rubber', 'Plastic'] },
  { world: 2, name: 'Clamp',      ingredients: ['Wood', 'Metal', 'Rubber'] },
  { world: 2, name: 'Fixture',    ingredients: ['Wood', 'Metal', 'Plastic'] },
  { world: 2, name: 'Grip',       ingredients: ['Glass', 'Rubber', 'Plastic'] },
  { world: 2, name: 'Machine',    ingredients: ['Wood', 'Metal', 'Glass', 'Rubber'] },
  { world: 2, name: 'Device',     ingredients: ['Metal', 'Glass', 'Rubber', 'Plastic'] },
  { world: 2, name: 'Cabinet',    ingredients: ['Wood', 'Glass', 'Rubber', 'Plastic'] },
  { world: 2, name: 'Console',    ingredients: ['Wood', 'Metal', 'Rubber', 'Plastic'] },
  { world: 2, name: 'Toolkit',    ingredients: ['Wood', 'Metal', 'Glass', 'Plastic'] },
  { world: 2, name: 'Core',       ingredients: ['Wood', 'Metal', 'Glass', 'Rubber', 'Plastic'] },

  // ── World 3 — Machines & Power ────────────────────────────────────────────
  { world: 3, name: 'Wire',      ingredients: ['Metal', 'Electricity'] },
  { world: 3, name: 'Gasket',    ingredients: ['Rubber', 'Plastic'] },
  { world: 3, name: 'Pipe',      ingredients: ['Metal', 'Plastic'] },
  { world: 3, name: 'Switch',    ingredients: ['Metal', 'Glass'] },
  { world: 3, name: 'Coil',      ingredients: ['Metal', 'Rubber'] },
  { world: 3, name: 'Cell',      ingredients: ['Glass', 'Electricity'] },
  { world: 3, name: 'Tank',      ingredients: ['Plastic', 'Fuel'] },
  { world: 3, name: 'Valve',     ingredients: ['Rubber', 'Fuel'] },
  { world: 3, name: 'Flare',     ingredients: ['Glass', 'Fuel'] },
  { world: 3, name: 'Cable',     ingredients: ['Rubber', 'Electricity'] },
  { world: 3, name: 'Goggle',    ingredients: ['Glass', 'Rubber'] },
  { world: 3, name: 'Chip',      ingredients: ['Electricity', 'Plastic'] },
  { world: 3, name: 'Screen',    ingredients: ['Glass', 'Plastic'] },
  { world: 3, name: 'Burner',    ingredients: ['Fuel', 'Metal'] },
  { world: 3, name: 'Welder',    ingredients: ['Electricity', 'Fuel'] },
  { world: 3, name: 'Motor',          ingredients: ['Metal', 'Electricity', 'Fuel'] },
  { world: 3, name: 'Sensor',         ingredients: ['Glass', 'Plastic', 'Electricity'] },
  { world: 3, name: 'Pump',           ingredients: ['Metal', 'Rubber', 'Fuel'] },
  { world: 3, name: 'Filter',         ingredients: ['Plastic', 'Glass', 'Rubber'] },
  { world: 3, name: 'Solenoid',       ingredients: ['Electricity', 'Metal', 'Rubber'] },
  { world: 3, name: 'Lantern',        ingredients: ['Fuel', 'Glass', 'Plastic'] },
  { world: 3, name: 'Vacuum Tube',    ingredients: ['Electricity', 'Glass', 'Rubber'] },
  { world: 3, name: 'Canister',       ingredients: ['Fuel', 'Metal', 'Plastic'] },
  { world: 3, name: 'Gauge',          ingredients: ['Glass', 'Metal', 'Rubber'] },
  { world: 3, name: 'Lighthouse',     ingredients: ['Electricity', 'Fuel', 'Glass'] },
  { world: 3, name: 'Visor',          ingredients: ['Glass', 'Metal', 'Plastic'] },
  { world: 3, name: 'Dynamo',         ingredients: ['Electricity', 'Fuel', 'Rubber'] },
  { world: 3, name: 'Battery',        ingredients: ['Electricity', 'Fuel', 'Plastic'] },
  { world: 3, name: 'Relay',          ingredients: ['Electricity', 'Glass', 'Metal'] },
  { world: 3, name: 'Circuit',        ingredients: ['Electricity', 'Metal', 'Plastic'] },
  { world: 3, name: 'Hose',           ingredients: ['Fuel', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Piston',         ingredients: ['Metal', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Cartridge',      ingredients: ['Electricity', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Nozzle',         ingredients: ['Fuel', 'Glass', 'Rubber'] },
  { world: 3, name: 'Turbine',        ingredients: ['Fuel', 'Glass', 'Metal'] },
  { world: 3, name: 'Generator',       ingredients: ['Metal', 'Rubber', 'Electricity', 'Fuel'] },
  { world: 3, name: 'Reactor',         ingredients: ['Metal', 'Glass', 'Electricity', 'Fuel'] },
  { world: 3, name: 'Amplifier',       ingredients: ['Electricity', 'Glass', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Transformer',     ingredients: ['Electricity', 'Glass', 'Metal', 'Plastic'] },
  { world: 3, name: 'Compressor',      ingredients: ['Fuel', 'Glass', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Furnace',         ingredients: ['Fuel', 'Metal', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Regulator',       ingredients: ['Electricity', 'Metal', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Pressure Vessel', ingredients: ['Fuel', 'Glass', 'Metal', 'Rubber'] },
  { world: 3, name: 'Terminal',        ingredients: ['Electricity', 'Fuel', 'Metal', 'Plastic'] },
  { world: 3, name: 'Exhaust',         ingredients: ['Electricity', 'Fuel', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Floodlight',      ingredients: ['Electricity', 'Fuel', 'Glass', 'Rubber'] },
  { world: 3, name: 'Cockpit',         ingredients: ['Glass', 'Metal', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Processor',       ingredients: ['Electricity', 'Glass', 'Metal', 'Rubber'] },
  { world: 3, name: 'Powercore',       ingredients: ['Electricity', 'Fuel', 'Metal', 'Rubber', 'Plastic'] },
  { world: 3, name: 'Rig',             ingredients: ['Electricity', 'Fuel', 'Glass', 'Metal', 'Rubber'] },
  { world: 3, name: 'Capsule',         ingredients: ['Electricity', 'Fuel', 'Glass', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Network',         ingredients: ['Electricity', 'Glass', 'Metal', 'Plastic', 'Rubber'] },
  { world: 3, name: 'System',          ingredients: ['Fuel', 'Glass', 'Metal', 'Plastic', 'Rubber'] },
  { world: 3, name: 'Engine',          ingredients: ['Metal', 'Rubber', 'Plastic', 'Glass', 'Electricity', 'Fuel'] },

  // ── World 4 — Chemistry Lab ───────────────────────────────────────────────
  { world: 4, name: 'Brine',      ingredients: ['Water', 'Heat'] },
  { world: 4, name: 'Vapor',      ingredients: ['Water', 'Gas'] },
  { world: 4, name: 'Oxide',      ingredients: ['Heat', 'Metal'] },
  { world: 4, name: 'Limestone',  ingredients: ['Carbon', 'Acid'] },
  { world: 4, name: 'Salt',       ingredients: ['Acid', 'Base'] },
  { world: 4, name: 'Ink',        ingredients: ['Water', 'Carbon'] },
  { world: 4, name: 'Alloy',      ingredients: ['Metal', 'Heat'] },
  { world: 4, name: 'Foam',       ingredients: ['Gas', 'Water'] },
  { world: 4, name: 'Resin',      ingredients: ['Carbon', 'Heat'] },
  { world: 4, name: 'Etch',       ingredients: ['Acid', 'Metal'] },
  { world: 4, name: 'Alkali',     ingredients: ['Base', 'Water'] },
  { world: 4, name: 'Coal',       ingredients: ['Metal', 'Carbon'] },
  { world: 4, name: 'Arc Plasma', ingredients: ['Gas', 'Heat'] },
  { world: 4, name: 'Rust',       ingredients: ['Water', 'Metal'] },
  { world: 4, name: 'Blight',     ingredients: ['Water', 'Acid'] },
  { world: 4, name: 'Smog',       ingredients: ['Gas', 'Carbon'] },
  { world: 4, name: 'Ingot',      ingredients: ['Metal', 'Gas'] },
  { world: 4, name: 'Acid Cloud', ingredients: ['Gas', 'Acid'] },
  { world: 4, name: 'Cinder',     ingredients: ['Heat', 'Acid'] },
  { world: 4, name: 'Slurry',     ingredients: ['Water', 'Base', 'Carbon'] },
  { world: 4, name: 'Potion',     ingredients: ['Water', 'Heat', 'Acid'] },
  { world: 4, name: 'Compound',   ingredients: ['Carbon', 'Metal', 'Base'] },
  { world: 4, name: 'Solvent',    ingredients: ['Water', 'Gas', 'Acid'] },
  { world: 4, name: 'Tonic',      ingredients: ['Water', 'Heat', 'Gas'] },
  { world: 4, name: 'Calcium',    ingredients: ['Water', 'Heat', 'Carbon'] },
  { world: 4, name: 'Deposit',    ingredients: ['Water', 'Heat', 'Metal'] },
  { world: 4, name: 'Cement',     ingredients: ['Water', 'Heat', 'Base'] },
  { world: 4, name: 'Haze',       ingredients: ['Water', 'Gas', 'Carbon'] },
  { world: 4, name: 'Dross',      ingredients: ['Water', 'Gas', 'Metal'] },
  { world: 4, name: 'Spray',      ingredients: ['Water', 'Gas', 'Base'] },
  { world: 4, name: 'Pigment',    ingredients: ['Water', 'Carbon', 'Metal'] },
  { world: 4, name: 'Reagent',    ingredients: ['Water', 'Carbon', 'Acid'] },
  { world: 4, name: 'Lotion',     ingredients: ['Water', 'Metal', 'Acid'] },
  { world: 4, name: 'Rinse',      ingredients: ['Water', 'Metal', 'Base'] },
  { world: 4, name: 'Antidote',   ingredients: ['Water', 'Acid', 'Base'] },
  { world: 4, name: 'Graphite',   ingredients: ['Heat', 'Gas', 'Carbon'] },
  { world: 4, name: 'Smelt',      ingredients: ['Heat', 'Gas', 'Metal'] },
  { world: 4, name: 'Fume',       ingredients: ['Heat', 'Gas', 'Acid'] },
  { world: 4, name: 'Calciner',   ingredients: ['Heat', 'Gas', 'Base'] },
  { world: 4, name: 'Crucible',   ingredients: ['Heat', 'Carbon', 'Metal'] },
  { world: 4, name: 'Char',       ingredients: ['Heat', 'Carbon', 'Acid'] },
  { world: 4, name: 'Blaze',      ingredients: ['Heat', 'Metal', 'Acid'] },
  { world: 4, name: 'Quench',     ingredients: ['Heat', 'Metal', 'Base'] },
  { world: 4, name: 'Flash',      ingredients: ['Heat', 'Acid', 'Base'] },
  { world: 4, name: 'Rocket',     ingredients: ['Gas', 'Carbon', 'Metal'] },
  { world: 4, name: 'Fumarate',   ingredients: ['Gas', 'Carbon', 'Acid'] },
  { world: 4, name: 'Cloud',      ingredients: ['Gas', 'Carbon', 'Base'] },
  { world: 4, name: 'Corrosion',  ingredients: ['Gas', 'Metal', 'Acid'] },
  { world: 4, name: 'Vent',       ingredients: ['Gas', 'Metal', 'Base'] },
  { world: 4, name: 'Aerosol',    ingredients: ['Gas', 'Acid', 'Base'] },
  { world: 4, name: 'Tarnish',    ingredients: ['Carbon', 'Metal', 'Acid'] },
  { world: 4, name: 'Vinegar',    ingredients: ['Carbon', 'Acid', 'Base'] },
  { world: 4, name: 'Patina',     ingredients: ['Metal', 'Acid', 'Base'] },
  { world: 4, name: 'Converter',  ingredients: ['Heat', 'Metal', 'Acid', 'Base'] },
  { world: 4, name: 'Formula',    ingredients: ['Water', 'Carbon', 'Gas', 'Heat'] },
  { world: 4, name: 'Mixture',    ingredients: ['Water', 'Heat', 'Gas', 'Carbon', 'Metal'] },
  { world: 4, name: 'Solution',   ingredients: ['Water', 'Heat', 'Gas', 'Carbon', 'Metal', 'Acid', 'Base'] },

  // ── World 5 — Quantum Realm ───────────────────────────────────────────────
  { world: 5, name: 'Arc',          ingredients: ['Wave', 'Charge'] },
  { world: 5, name: 'Dark Energy',  ingredients: ['Void', 'Field'] },
  { world: 5, name: 'Echo',         ingredients: ['Wave', 'Void'] },
  { world: 5, name: 'Electron',     ingredients: ['Particle', 'Field'] },
  { world: 5, name: 'Gyroscope',    ingredients: ['Spin', 'Field'] },
  { world: 5, name: 'Ion',          ingredients: ['Particle', 'Charge'] },
  { world: 5, name: 'Lightning',    ingredients: ['Energy', 'Charge'] },
  { world: 5, name: 'Magnet',       ingredients: ['Field', 'Charge'] },
  { world: 5, name: 'Wavicle',      ingredients: ['Particle', 'Wave'] },
  { world: 5, name: 'Plasmoid',     ingredients: ['Energy', 'Spin'] },
  { world: 5, name: 'Quark',        ingredients: ['Particle', 'Spin'] },
  { world: 5, name: 'Radiation',    ingredients: ['Wave', 'Energy'] },
  { world: 5, name: 'Signal',       ingredients: ['Wave', 'Field'] },
  { world: 5, name: 'Singularity',  ingredients: ['Energy', 'Void'] },
  { world: 5, name: 'Torque',       ingredients: ['Spin', 'Charge'] },
  { world: 5, name: 'Vacuum',       ingredients: ['Void', 'Charge'] },
  { world: 5, name: 'Vortex',       ingredients: ['Void', 'Spin'] },
  { world: 5, name: 'Anomaly',       ingredients: ['Void', 'Spin', 'Observer'] },
  { world: 5, name: 'Atom',          ingredients: ['Particle', 'Wave', 'Field'] },
  { world: 5, name: 'Aura',          ingredients: ['Energy', 'Spin', 'Charge'] },
  { world: 5, name: 'Solenoid Field',ingredients: ['Field', 'Spin', 'Charge'] },
  { world: 5, name: 'Entanglement',  ingredients: ['Particle', 'Field', 'Charge'] },
  { world: 5, name: 'Horizon',       ingredients: ['Energy', 'Void', 'Field'] },
  { world: 5, name: 'Neutrino',      ingredients: ['Particle', 'Void', 'Spin'] },
  { world: 5, name: 'Prism',         ingredients: ['Wave', 'Field', 'Observer'] },
  { world: 5, name: 'Resonance',     ingredients: ['Wave', 'Energy', 'Spin'] },
  { world: 5, name: 'Spectrum',      ingredients: ['Wave', 'Energy', 'Observer'] },
  { world: 5, name: 'Superposition', ingredients: ['Particle', 'Wave', 'Observer'] },
  { world: 5, name: 'Tunnel',        ingredients: ['Particle', 'Energy', 'Void'] },
  { world: 5, name: 'Fold',          ingredients: ['Wave', 'Void', 'Field'] },
  { world: 5, name: 'Many Worlds',   ingredients: ['Wave', 'Void', 'Field', 'Observer'] },
  { world: 5, name: 'Plasma Ball',   ingredients: ['Energy', 'Spin', 'Field', 'Charge'] },
  { world: 5, name: 'Decay',         ingredients: ['Particle', 'Wave', 'Energy', 'Void'] },
  { world: 5, name: 'Schrodinger',   ingredients: ['Particle', 'Void', 'Spin', 'Observer'] },
  { world: 5, name: 'String',        ingredients: ['Wave', 'Energy', 'Void', 'Spin'] },
  { world: 5, name: 'Wave Function', ingredients: ['Particle', 'Wave', 'Spin', 'Field'] },
  { world: 5, name: 'Dark Matter',   ingredients: ['Particle', 'Void', 'Spin', 'Field', 'Observer'] },
  { world: 5, name: 'Quantum Realm', ingredients: ['Particle', 'Wave', 'Energy', 'Spin', 'Field'] },
  { world: 5, name: 'Collider',      ingredients: ['Energy', 'Field', 'Spin', 'Charge', 'Observer'] },
  { world: 5, name: 'Spacetime',     ingredients: ['Wave', 'Energy', 'Void', 'Field', 'Observer'] },
  { world: 5, name: 'Consciousness', ingredients: ['Wave', 'Void', 'Field', 'Observer', 'Charge', 'Spin'] },
  { world: 5, name: 'Hadron',        ingredients: ['Particle', 'Wave', 'Spin', 'Field', 'Charge', 'Energy'] },
  { world: 5, name: 'Event',         ingredients: ['Wave', 'Energy', 'Void', 'Spin', 'Field', 'Observer', 'Charge'] },
  { world: 5, name: 'God Particle',  ingredients: ['Particle', 'Wave', 'Energy', 'Void', 'Spin', 'Field', 'Observer'] },
  { world: 5, name: 'Unified Field', ingredients: ['Particle', 'Wave', 'Energy', 'Void', 'Spin', 'Field', 'Observer', 'Charge'] },

  // ── World 6 — Biology ─────────────────────────────────────────────────────
  { world: 6, name: 'Corrode',      ingredients: ['Water', 'Acid'] },
  { world: 6, name: 'Bile',         ingredients: ['Acid', 'Enzyme'] },
  { world: 6, name: 'Blister',      ingredients: ['Heat', 'Acid'] },
  { world: 6, name: 'Breath',       ingredients: ['Oxygen', 'Heat'] },
  { world: 6, name: 'Bubble',       ingredients: ['Water', 'Oxygen'] },
  { world: 6, name: 'Activator',    ingredients: ['Cell', 'Enzyme'] },
  { world: 6, name: 'Chlorophyll',  ingredients: ['Cell', 'Light'] },
  { world: 6, name: 'Char',         ingredients: ['Carbon', 'Heat'] },
  { world: 6, name: 'Digest',       ingredients: ['Water', 'Enzyme'] },
  { world: 6, name: 'Fever',        ingredients: ['Cell', 'Heat'] },
  { world: 6, name: 'Glucose',      ingredients: ['Cell', 'Carbon'] },
  { world: 6, name: 'Hormone',      ingredients: ['Nitrogen', 'Enzyme'] },
  { world: 6, name: 'Ice Crystal',  ingredients: ['Water', 'Light'] },
  { world: 6, name: 'Membrane',     ingredients: ['Cell', 'Water'] },
  { world: 6, name: 'Nucleus',      ingredients: ['Cell', 'Nitrogen'] },
  { world: 6, name: 'Oxygen Cycle', ingredients: ['Oxygen', 'Carbon'] },
  { world: 6, name: 'Ozone',        ingredients: ['Oxygen', 'Light'] },
  { world: 6, name: 'Pigment',      ingredients: ['Light', 'Carbon'] },
  { world: 6, name: 'Pheromone',    ingredients: ['Light', 'Nitrogen'] },
  { world: 6, name: 'Protein',      ingredients: ['Carbon', 'Nitrogen'] },
  { world: 6, name: 'Rain',         ingredients: ['Water', 'Nitrogen'] },
  { world: 6, name: 'Respiration',  ingredients: ['Cell', 'Oxygen'] },
  { world: 6, name: 'Rot',          ingredients: ['Carbon', 'Acid'] },
  { world: 6, name: 'Sap',          ingredients: ['Water', 'Carbon'] },
  { world: 6, name: 'Sight',        ingredients: ['Light', 'Enzyme'] },
  { world: 6, name: 'Sweat',        ingredients: ['Water', 'Heat'] },
  { world: 6, name: 'Sunburn',      ingredients: ['Light', 'Acid'] },
  { world: 6, name: 'Sting',        ingredients: ['Cell', 'Acid'] },
  { world: 6, name: 'Warmth',       ingredients: ['Light', 'Heat'] },
  { world: 6, name: 'Algae',        ingredients: ['Cell', 'Water', 'Light'] },
  { world: 6, name: 'Amber',        ingredients: ['Carbon', 'Heat', 'Acid'] },
  { world: 6, name: 'Antibody',     ingredients: ['Cell', 'Nitrogen', 'Enzyme'] },
  { world: 6, name: 'Bacteria',     ingredients: ['Cell', 'Water', 'Acid'] },
  { world: 6, name: 'Blood',        ingredients: ['Cell', 'Water', 'Oxygen'] },
  { world: 6, name: 'Ferment',      ingredients: ['Carbon', 'Enzyme', 'Acid'] },
  { world: 6, name: 'Fossil',       ingredients: ['Carbon', 'Nitrogen', 'Heat'] },
  { world: 6, name: 'Fungi',        ingredients: ['Carbon', 'Nitrogen', 'Acid'] },
  { world: 6, name: 'Photosynthesis',ingredients: ['Cell', 'Light', 'Carbon'] },
  { world: 6, name: 'Root',         ingredients: ['Cell', 'Water', 'Carbon'] },
  { world: 6, name: 'Seed',         ingredients: ['Cell', 'Carbon', 'Nitrogen'] },
  { world: 6, name: 'Toxin',        ingredients: ['Cell', 'Acid', 'Nitrogen'] },
  { world: 6, name: 'Brain',        ingredients: ['Cell', 'Oxygen', 'Nitrogen', 'Heat'] },
  { world: 6, name: 'DNA',          ingredients: ['Cell', 'Carbon', 'Nitrogen', 'Acid'] },
  { world: 6, name: 'Egg',          ingredients: ['Cell', 'Water', 'Nitrogen', 'Heat'] },
  { world: 6, name: 'Immune Cell',  ingredients: ['Cell', 'Water', 'Enzyme', 'Nitrogen'] },
  { world: 6, name: 'Leaf',         ingredients: ['Cell', 'Light', 'Water', 'Carbon'] },
  { world: 6, name: 'Mutation',     ingredients: ['Cell', 'Light', 'Acid', 'Enzyme'] },
  { world: 6, name: 'Neuron',       ingredients: ['Cell', 'Oxygen', 'Nitrogen', 'Enzyme'] },
  { world: 6, name: 'Ecosystem',    ingredients: ['Cell', 'Water', 'Light', 'Carbon', 'Oxygen'] },
  { world: 6, name: 'Embryo',       ingredients: ['Cell', 'Water', 'Nitrogen', 'Heat', 'Carbon'] },
  { world: 6, name: 'Parasite',     ingredients: ['Cell', 'Acid', 'Nitrogen', 'Carbon', 'Enzyme'] },
  { world: 6, name: 'Evolution',    ingredients: ['Cell', 'Water', 'Carbon', 'Nitrogen', 'Oxygen', 'Heat'] },
  { world: 6, name: 'Genome',       ingredients: ['Cell', 'Light', 'Carbon', 'Nitrogen', 'Acid', 'Enzyme'] },
  { world: 6, name: 'Cortex',       ingredients: ['Cell', 'Oxygen', 'Nitrogen', 'Heat', 'Enzyme', 'Water', 'Carbon'] },
  { world: 6, name: 'Symbiosis',    ingredients: ['Cell', 'Light', 'Carbon', 'Nitrogen', 'Acid', 'Oxygen', 'Enzyme'] },
  { world: 6, name: 'Primordial Soup', ingredients: ['Water', 'Light', 'Carbon', 'Oxygen', 'Nitrogen', 'Heat', 'Acid', 'Enzyme'] },
  { world: 6, name: 'Life Force',   ingredients: ['Cell', 'Water', 'Light', 'Carbon', 'Oxygen', 'Nitrogen', 'Heat', 'Acid', 'Enzyme'] },

  // ── World 7 — Civilization ────────────────────────────────────────────────
  { world: 7, name: 'Ancestor',     ingredients: ['Time', 'Spirit'] },
  { world: 7, name: 'Aqueduct',     ingredients: ['Metal', 'Water'] },
  { world: 7, name: 'Armor',        ingredients: ['Metal', 'Labor'] },
  { world: 7, name: 'Ember',        ingredients: ['Fire', 'Time'] },
  { world: 7, name: 'Axe',          ingredients: ['Stone', 'Wood'] },
  { world: 7, name: 'Beacon',       ingredients: ['Fire', 'Knowledge'] },
  { world: 7, name: 'Blade',        ingredients: ['Metal', 'Fire'] },
  { world: 7, name: 'Boat',         ingredients: ['Wood', 'Water'] },
  { world: 7, name: 'Calendar',     ingredients: ['Knowledge', 'Soil'] },
  { world: 7, name: 'Charcoal',     ingredients: ['Wood', 'Fire'] },
  { world: 7, name: 'Clay',         ingredients: ['Water', 'Soil'] },
  { world: 7, name: 'Coin',         ingredients: ['Metal', 'Knowledge'] },
  { world: 7, name: 'Craft',        ingredients: ['Knowledge', 'Labor'] },
  { world: 7, name: 'Crop',         ingredients: ['Labor', 'Soil'] },
  { world: 7, name: 'Farm',         ingredients: ['Wood', 'Soil'] },
  { world: 7, name: 'Flood',        ingredients: ['Water', 'Time'] },
  { world: 7, name: 'Forge',        ingredients: ['Stone', 'Fire'] },
  { world: 7, name: 'Gravel',       ingredients: ['Stone', 'Soil'] },
  { world: 7, name: 'Harvest',      ingredients: ['Fire', 'Soil'] },
  { world: 7, name: 'Idol',         ingredients: ['Metal', 'Spirit'] },
  { world: 7, name: 'Irrigation',   ingredients: ['Labor', 'Water'] },
  { world: 7, name: 'Pottery Kiln', ingredients: ['Fire', 'Labor'] },
  { world: 7, name: 'Lumber',       ingredients: ['Wood', 'Labor'] },
  { world: 7, name: 'Map',          ingredients: ['Knowledge', 'Water'] },
  { world: 7, name: 'Mine',         ingredients: ['Metal', 'Soil'] },
  { world: 7, name: 'Obelisk',      ingredients: ['Labor', 'Time'] },
  { world: 7, name: 'Myth',         ingredients: ['Knowledge', 'Spirit'] },
  { world: 7, name: 'Prayer',       ingredients: ['Labor', 'Spirit'] },
  { world: 7, name: 'Quarry',       ingredients: ['Stone', 'Labor'] },
  { world: 7, name: 'Relic',        ingredients: ['Metal', 'Time'] },
  { world: 7, name: 'Ritual',       ingredients: ['Fire', 'Spirit'] },
  { world: 7, name: 'Roots',        ingredients: ['Soil', 'Time'] },
  { world: 7, name: 'Ruin',         ingredients: ['Stone', 'Time'] },
  { world: 7, name: 'Sacred Ground',ingredients: ['Soil', 'Spirit'] },
  { world: 7, name: 'Scroll',       ingredients: ['Wood', 'Knowledge'] },
  { world: 7, name: 'Shrine',       ingredients: ['Stone', 'Spirit'] },
  { world: 7, name: 'Spirit Well',  ingredients: ['Water', 'Spirit'] },
  { world: 7, name: 'Geyser',       ingredients: ['Fire', 'Water'] },
  { world: 7, name: 'Stump',        ingredients: ['Wood', 'Time'] },
  { world: 7, name: 'Tablet',       ingredients: ['Stone', 'Knowledge'] },
  { world: 7, name: 'Totem',        ingredients: ['Wood', 'Spirit'] },
  { world: 7, name: 'Well',         ingredients: ['Stone', 'Water'] },
  { world: 7, name: 'Wisdom',       ingredients: ['Knowledge', 'Time'] },
  { world: 7, name: 'Arch',         ingredients: ['Stone', 'Labor', 'Knowledge'] },
  { world: 7, name: 'Bread',        ingredients: ['Fire', 'Labor', 'Soil'] },
  { world: 7, name: 'Bridge',       ingredients: ['Stone', 'Wood', 'Water'] },
  { world: 7, name: 'Canoe',        ingredients: ['Wood', 'Water', 'Labor'] },
  { world: 7, name: 'Sextant',      ingredients: ['Metal', 'Knowledge', 'Water'] },
  { world: 7, name: 'Crown',        ingredients: ['Metal', 'Knowledge', 'Spirit'] },
  { world: 7, name: 'Dam',          ingredients: ['Stone', 'Water', 'Labor'] },
  { world: 7, name: 'Hammer',       ingredients: ['Stone', 'Metal', 'Labor'] },
  { world: 7, name: 'Longbow',      ingredients: ['Wood', 'Knowledge', 'Labor'] },
  { world: 7, name: 'Oracle',       ingredients: ['Knowledge', 'Spirit', 'Time'] },
  { world: 7, name: 'Plow',         ingredients: ['Wood', 'Metal', 'Soil'] },
  { world: 7, name: 'Vision',       ingredients: ['Knowledge', 'Spirit', 'Time'] },
  { world: 7, name: 'Sword',        ingredients: ['Metal', 'Fire', 'Labor'] },
  { world: 7, name: 'Tower',        ingredients: ['Stone', 'Labor', 'Time'] },
  { world: 7, name: 'Wheel',        ingredients: ['Stone', 'Wood', 'Labor'] },
  { world: 7, name: 'Manuscript',   ingredients: ['Knowledge', 'Labor', 'Time'] },
  { world: 7, name: 'Army',         ingredients: ['Metal', 'Fire', 'Labor', 'Time'] },
  { world: 7, name: 'Harbor',       ingredients: ['Stone', 'Wood', 'Water', 'Labor'] },
  { world: 7, name: 'Library',      ingredients: ['Wood', 'Knowledge', 'Labor', 'Time'] },
  { world: 7, name: 'Market',       ingredients: ['Metal', 'Labor', 'Knowledge', 'Water'] },
  { world: 7, name: 'Palace',       ingredients: ['Stone', 'Metal', 'Knowledge', 'Labor'] },
  { world: 7, name: 'Religion',     ingredients: ['Knowledge', 'Spirit', 'Labor', 'Time'] },
  { world: 7, name: 'Road',         ingredients: ['Stone', 'Labor', 'Time', 'Water'] },
  { world: 7, name: 'Temple',       ingredients: ['Stone', 'Labor', 'Knowledge', 'Spirit'] },
  { world: 7, name: 'Cathedral',    ingredients: ['Stone', 'Labor', 'Knowledge', 'Spirit', 'Time'] },
  { world: 7, name: 'Colosseum',    ingredients: ['Stone', 'Metal', 'Labor', 'Knowledge', 'Time'] },
  { world: 7, name: 'Fleet',        ingredients: ['Wood', 'Water', 'Metal', 'Fire', 'Labor'] },
  { world: 7, name: 'Pyramid',      ingredients: ['Stone', 'Labor', 'Knowledge', 'Time', 'Soil'] },
  { world: 7, name: 'Dynasty',      ingredients: ['Metal', 'Knowledge', 'Labor', 'Time', 'Fire', 'Water'] },
  { world: 7, name: 'Legend',       ingredients: ['Knowledge', 'Spirit', 'Time', 'Labor', 'Fire', 'Wood'] },
  { world: 7, name: 'Revolution',   ingredients: ['Metal', 'Fire', 'Labor', 'Knowledge', 'Time', 'Stone'] },
  { world: 7, name: 'Civilization', ingredients: ['Stone', 'Wood', 'Metal', 'Fire', 'Labor', 'Water', 'Soil'] },
  { world: 7, name: 'Golden Age',   ingredients: ['Metal', 'Knowledge', 'Labor', 'Time', 'Spirit', 'Fire', 'Water'] },
  { world: 7, name: 'Empire',       ingredients: ['Stone', 'Wood', 'Metal', 'Fire', 'Knowledge', 'Labor', 'Time', 'Soil', 'Water', 'Spirit'] },

  // ── World 8 — Cosmos ──────────────────────────────────────────────────────
  { world: 8, name: 'Cryo Shadow',  ingredients: ['Ice', 'Dark Matter'] },
  { world: 8, name: 'Void Era',     ingredients: ['Time', 'Dark Matter'] },
  { world: 8, name: 'Dark Field',   ingredients: ['Magnetism', 'Dark Matter'] },
  { world: 8, name: 'Phantom Cloud',ingredients: ['Gas', 'Dark Matter'] },
  { world: 8, name: 'Dark Halo',    ingredients: ['Void', 'Dark Matter'] },
  { world: 8, name: 'Dark Mass',    ingredients: ['Gravity', 'Dark Matter'] },
  { world: 8, name: 'Shadow Flare', ingredients: ['Plasma', 'Dark Matter'] },
  { world: 8, name: 'Abyss',        ingredients: ['Void', 'Radiation'] },
  { world: 8, name: 'Dead Zone',    ingredients: ['Void', 'Magnetism'] },
  { world: 8, name: 'Debris',       ingredients: ['Dust', 'Radiation'] },
  { world: 8, name: 'Decay',        ingredients: ['Radiation', 'Dark Matter'] },
  { world: 8, name: 'Deep Space',   ingredients: ['Void', 'Gas'] },
  { world: 8, name: 'Dust Age',     ingredients: ['Dust', 'Time'] },
  { world: 8, name: 'Dust Storm',   ingredients: ['Dust', 'Magnetism'] },
  { world: 8, name: 'Dust Web',     ingredients: ['Dust', 'Dark Matter'] },
  { world: 8, name: 'Epoch',        ingredients: ['Time', 'Magnetism'] },
  { world: 8, name: 'Eruption',     ingredients: ['Plasma', 'Dust'] },
  { world: 8, name: 'Event Horizon',ingredients: ['Void', 'Time'] },
  { world: 8, name: 'Flare',        ingredients: ['Plasma', 'Light'] },
  { world: 8, name: 'Ancient Light',ingredients: ['Light', 'Time'] },
  { world: 8, name: 'Frost',        ingredients: ['Light', 'Ice'] },
  { world: 8, name: 'Gas Cloud',    ingredients: ['Plasma', 'Gas'] },
  { world: 8, name: 'Ghost Star',   ingredients: ['Light', 'Dark Matter'] },
  { world: 8, name: 'Glacier',      ingredients: ['Dust', 'Ice'] },
  { world: 8, name: 'Half-Life',    ingredients: ['Time', 'Radiation'] },
  { world: 8, name: 'Ice Radiation',ingredients: ['Ice', 'Radiation'] },
  { world: 8, name: 'Laser',        ingredients: ['Light', 'Radiation'] },
  { world: 8, name: 'Lensing',      ingredients: ['Light', 'Gravity'] },
  { world: 8, name: 'Magnetar',     ingredients: ['Gravity', 'Magnetism'] },
  { world: 8, name: 'Magnetic Storm',ingredients: ['Magnetism', 'Radiation'] },
  { world: 8, name: 'Moon',         ingredients: ['Gravity', 'Ice'] },
  { world: 8, name: 'Nebula',       ingredients: ['Void', 'Dust'] },
  { world: 8, name: 'Neutron Star', ingredients: ['Gravity', 'Radiation'] },
  { world: 8, name: 'Orbit',        ingredients: ['Gravity', 'Plasma'] },
  { world: 8, name: 'Permafrost',   ingredients: ['Ice', 'Time'] },
  { world: 8, name: 'Planet',       ingredients: ['Gravity', 'Gas'] },
  { world: 8, name: 'Plasma Age',   ingredients: ['Plasma', 'Time'] },
  { world: 8, name: 'Polar Cap',    ingredients: ['Ice', 'Magnetism'] },
  { world: 8, name: 'Pulsar',       ingredients: ['Plasma', 'Radiation'] },
  { world: 8, name: 'Asteroid',     ingredients: ['Dust', 'Gravity'] },
  { world: 8, name: 'Shadow',       ingredients: ['Void', 'Light'] },
  { world: 8, name: 'Shockwave',    ingredients: ['Radiation', 'Gas'] },
  { world: 8, name: 'Solar Wind',   ingredients: ['Plasma', 'Magnetism'] },
  { world: 8, name: 'Emission Line',ingredients: ['Light', 'Gas'] },
  { world: 8, name: 'Star',         ingredients: ['Light', 'Plasma'] },
  { world: 8, name: 'Tail',         ingredients: ['Dust', 'Gas'] },
  { world: 8, name: 'Time Dilation',ingredients: ['Gravity', 'Time'] },
  { world: 8, name: 'Blazar',          ingredients: ['Void', 'Plasma', 'Radiation'] },
  { world: 8, name: 'Comet Storm',     ingredients: ['Ice', 'Dust', 'Gas'] },
  { world: 8, name: 'Dark Web',        ingredients: ['Void', 'Dark Matter', 'Gravity'] },
  { world: 8, name: 'Gamma Burst',     ingredients: ['Radiation', 'Plasma', 'Light'] },
  { world: 8, name: 'Ice Planet',      ingredients: ['Ice', 'Gravity', 'Gas'] },
  { world: 8, name: 'Magnetosphere',   ingredients: ['Gravity', 'Magnetism', 'Radiation'] },
  { world: 8, name: 'Nebula Core',     ingredients: ['Dust', 'Light', 'Radiation'] },
  { world: 8, name: 'Protostar',       ingredients: ['Dust', 'Gas', 'Gravity'] },
  { world: 8, name: 'Quasar',          ingredients: ['Void', 'Light', 'Gravity'] },
  { world: 8, name: 'Solar System',    ingredients: ['Gravity', 'Plasma', 'Gas'] },
  { world: 8, name: 'Supernova',       ingredients: ['Light', 'Plasma', 'Radiation'] },
  { world: 8, name: 'Time Rift',       ingredients: ['Time', 'Void', 'Gravity'] },
  { world: 8, name: 'Dark Galaxy',     ingredients: ['Void', 'Gravity', 'Dark Matter', 'Dust'] },
  { world: 8, name: 'Galaxy',          ingredients: ['Void', 'Light', 'Gravity', 'Dust'] },
  { world: 8, name: 'Ice Comet',       ingredients: ['Ice', 'Dust', 'Light', 'Gas'] },
  { world: 8, name: 'Magnetar Storm',  ingredients: ['Magnetism', 'Plasma', 'Radiation', 'Gas'] },
  { world: 8, name: 'Stellar Nursery', ingredients: ['Dust', 'Gas', 'Gravity', 'Light'] },
  { world: 8, name: 'White Dwarf',     ingredients: ['Light', 'Gravity', 'Plasma', 'Time'] },
  { world: 8, name: 'Cosmic Web',      ingredients: ['Void', 'Gravity', 'Dust', 'Gas', 'Dark Matter'] },
  { world: 8, name: 'Dark Collapse',   ingredients: ['Void', 'Gravity', 'Dark Matter', 'Time', 'Dust'] },
  { world: 8, name: 'Red Giant',       ingredients: ['Light', 'Plasma', 'Gas', 'Time', 'Gravity'] },
  { world: 8, name: 'Cosmic Dawn',     ingredients: ['Light', 'Plasma', 'Gas', 'Dust', 'Radiation', 'Time'] },
  { world: 8, name: 'Entropy',         ingredients: ['Void', 'Dark Matter', 'Time', 'Dust', 'Gas', 'Ice'] },
  { world: 8, name: 'Multiverse',      ingredients: ['Void', 'Time', 'Gravity', 'Light', 'Radiation', 'Ice'] },
  { world: 8, name: 'Dark Universe',   ingredients: ['Void', 'Dark Matter', 'Gravity', 'Ice', 'Dust', 'Gas', 'Time'] },
  { world: 8, name: 'Observable Universe', ingredients: ['Light', 'Gravity', 'Plasma', 'Dust', 'Gas', 'Time', 'Radiation'] },
  { world: 8, name: 'Inflation',       ingredients: ['Void', 'Light', 'Gravity', 'Plasma', 'Dust', 'Time', 'Magnetism', 'Radiation', 'Gas'] },
  { world: 8, name: 'Heat Death',      ingredients: ['Void', 'Light', 'Gravity', 'Dust', 'Ice', 'Time', 'Magnetism', 'Radiation', 'Gas', 'Dark Matter'] },
  { world: 8, name: 'Big Bang',        ingredients: ['Void', 'Light', 'Gravity', 'Plasma', 'Dust', 'Ice', 'Time', 'Magnetism', 'Radiation', 'Gas', 'Dark Matter'] },
];

// ── Per-world metadata ────────────────────────────────────────────────────────
export interface WorldCatalogInfo {
  world: number;
  name: string;
  grid: string;
  elements: string[];
  accent: string;       // solid accent color
  accentFaint: string;  // faint bg tint
  border: string;       // border rgba
  badgeBg: string;      // pill background
  badgeText: string;    // pill text
  numberBg: [string, string]; // gradient start/end for number box
}

export const WORLD_CATALOG: WorldCatalogInfo[] = [
  {
    world: 1, name: 'Nature Lab', grid: '4×4',
    elements: ['Wind', 'Earth', 'Fire', 'Water'],
    accent: '#10b981', accentFaint: 'rgba(16,185,129,0.10)',
    border: 'rgba(16,185,129,0.35)',
    badgeBg: 'rgba(16,185,129,0.15)', badgeText: '#34d399',
    numberBg: ['rgba(16,185,129,0.35)', 'rgba(52,211,153,0.25)'],
  },
  {
    world: 2, name: 'Materials Workshop', grid: '5×5',
    elements: ['Wood', 'Metal', 'Glass', 'Rubber', 'Plastic'],
    accent: '#f59e0b', accentFaint: 'rgba(245,158,11,0.10)',
    border: 'rgba(245,158,11,0.35)',
    badgeBg: 'rgba(245,158,11,0.15)', badgeText: '#fbbf24',
    numberBg: ['rgba(245,158,11,0.35)', 'rgba(251,191,36,0.25)'],
  },
  {
    world: 3, name: 'Machines & Power', grid: '6×6',
    elements: ['Metal', 'Rubber', 'Plastic', 'Glass', 'Electricity', 'Fuel'],
    accent: '#3b82f6', accentFaint: 'rgba(59,130,246,0.10)',
    border: 'rgba(59,130,246,0.35)',
    badgeBg: 'rgba(59,130,246,0.15)', badgeText: '#60a5fa',
    numberBg: ['rgba(59,130,246,0.35)', 'rgba(99,102,241,0.25)'],
  },
  {
    world: 4, name: 'Chemistry Lab', grid: '7×7',
    elements: ['Water', 'Heat', 'Gas', 'Carbon', 'Metal', 'Acid', 'Base'],
    accent: '#8b5cf6', accentFaint: 'rgba(139,92,246,0.10)',
    border: 'rgba(139,92,246,0.35)',
    badgeBg: 'rgba(139,92,246,0.15)', badgeText: '#a78bfa',
    numberBg: ['rgba(139,92,246,0.35)', 'rgba(167,139,250,0.25)'],
  },
  {
    world: 5, name: 'Quantum Realm', grid: '8×8',
    elements: ['Particle', 'Wave', 'Energy', 'Void', 'Spin', 'Field', 'Observer', 'Charge'],
    accent: '#06b6d4', accentFaint: 'rgba(6,182,212,0.10)',
    border: 'rgba(6,182,212,0.35)',
    badgeBg: 'rgba(6,182,212,0.15)', badgeText: '#22d3ee',
    numberBg: ['rgba(6,182,212,0.35)', 'rgba(20,184,166,0.25)'],
  },
  {
    world: 6, name: 'Biology', grid: '9×9',
    elements: ['Cell', 'Water', 'Light', 'Carbon', 'Oxygen', 'Nitrogen', 'Heat', 'Acid', 'Enzyme'],
    accent: '#84cc16', accentFaint: 'rgba(132,204,22,0.10)',
    border: 'rgba(132,204,22,0.35)',
    badgeBg: 'rgba(132,204,22,0.15)', badgeText: '#a3e635',
    numberBg: ['rgba(132,204,22,0.35)', 'rgba(163,230,53,0.25)'],
  },
  {
    world: 7, name: 'Civilization', grid: '10×10',
    elements: ['Stone', 'Wood', 'Metal', 'Fire', 'Knowledge', 'Labor', 'Time', 'Soil', 'Water', 'Spirit'],
    accent: '#f97316', accentFaint: 'rgba(249,115,22,0.10)',
    border: 'rgba(249,115,22,0.35)',
    badgeBg: 'rgba(249,115,22,0.15)', badgeText: '#fb923c',
    numberBg: ['rgba(249,115,22,0.35)', 'rgba(234,179,8,0.25)'],
  },
  {
    world: 8, name: 'Cosmos', grid: '11×11',
    elements: ['Void', 'Light', 'Gravity', 'Plasma', 'Dust', 'Ice', 'Time', 'Magnetism', 'Radiation', 'Gas', 'Dark Matter'],
    accent: '#7c3aed', accentFaint: 'rgba(124,58,237,0.10)',
    border: 'rgba(124,58,237,0.35)',
    badgeBg: 'rgba(124,58,237,0.15)', badgeText: '#a78bfa',
    numberBg: ['rgba(124,58,237,0.35)', 'rgba(99,102,241,0.25)'],
  },
];
