kind = "mobile"
previewPath = "/"
title = "Alchegrid"
version = "1.0.0"
id = "artifacts/alchegrid"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25433

[services.development]
run = "pnpm --filter @workspace/alchegrid run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/alchegrid", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/alchegrid", "run", "serve" ]

[services.env]
PORT = "25433"
BASE_PATH = "/"
